# Generated by Django 4.1.7 on 2023-12-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=None, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('salary', models.FloatField(null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
            ],
            bases=('app_account.account',),
        ),
        migrations.CreateModel(
            name='OrderHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField(null=True)),
                ('status_current', models.CharField(max_length=1000, null=True)),
                ('action_by_type_user', models.CharField(max_length=1000, null=True)),
                ('id_user', models.IntegerField(null=True)),
                ('date_modifided', models.DateField(default=None, null=True)),
                ('id_staff', models.ForeignKey(db_column='ID_staff', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_staff.staff')),
            ],
        ),
    ]
