# Generated by Django 4.1.7 on 2023-12-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_store', '0001_initial'),
        ('app_user', '0001_initial'),
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('cartid', models.ForeignKey(blank=True, db_column='CartID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cart.shoppingcart')),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('method', models.CharField(blank=True, db_column='ShippingMethod', max_length=255, null=True)),
                ('date_shipping', models.DateField(blank=True, db_column='DateShipping', null=True)),
                ('delayshipnote', models.CharField(blank=True, db_column='DelayShipNote', max_length=255, null=True)),
                ('price_shipping', models.FloatField(null=True)),
                ('address', models.ForeignKey(db_column='addressID', on_delete=django.db.models.deletion.CASCADE, to='app_user.addressshipping')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('isComplete', models.BooleanField(blank=True, default=True, null=True)),
                ('method', models.CharField(blank=True, db_column='Method', max_length=255, null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('amount', models.FloatField(null=True)),
                ('id_cart', models.ForeignKey(db_column='IDcart', on_delete=django.db.models.deletion.CASCADE, to='app_cart.shoppingcart')),
                ('id_shipping', models.ForeignKey(db_column='IDshipping', on_delete=django.db.models.deletion.CASCADE, to='app_order.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('cartline', models.OneToOneField(db_column='CartlineID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cart.cartline')),
                ('orderid', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='app_order.order')),
                ('product', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='app_store.book')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paymentid',
            field=models.OneToOneField(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, to='app_order.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingid',
            field=models.ForeignKey(blank=True, db_column='ShippingID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_order.shipping'),
        ),
    ]
