# Generated by Django 4.1.7 on 2023-12-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=None, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
            ],
            bases=('app_account.account',),
        ),
        migrations.CreateModel(
            name='AddressShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_receiver', models.CharField(max_length=50, null=True)),
                ('receiver_phone', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('ward', models.CharField(max_length=50, null=True)),
                ('address_detail', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
    ]
