# Generated by Django 4.1.7 on 2023-12-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_store', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(db_column='ID_cart', primary_key=True, serialize=False)),
                ('customerid', models.OneToOneField(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='app_user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cartline',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
                ('is_order', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_selected', models.BooleanField(default=False, null=True)),
                ('id_product', models.ForeignKey(db_column='ID_book', on_delete=django.db.models.deletion.CASCADE, to='app_store.book')),
                ('shoppingcartid', models.ForeignKey(db_column='ShoppingCartID', on_delete=django.db.models.deletion.CASCADE, to='app_cart.shoppingcart')),
            ],
        ),
    ]
